// Κείμενα διεπαφής για τις σελίδες δισκογραφίας (συνθέτης / δίσκος).
export const discDict = {
  el: {
    discographies: "Δισκογραφίες",
    discographiesKicker: "Το αρχείο των δίσκων",
    discographiesIntro:
      "Ολόκληρες δισκογραφίες, δίσκο-δίσκο: ποιος τραγούδησε, ποιος έγραψε τους στίχους, πότε και σε ποια εταιρεία κυκλοφόρησε — και, όπου υπάρχει πηγή, η ιστορία πίσω από τα τραγούδια.",
    openFile: "Άνοιξε τον φάκελο →",
    albumsCount: (n) => `${n} δίσκοι στο αρχείο`,
    composer: "Συνθέτης",
    backToComposer: (name) => `← Όλοι οι δίσκοι: ${name}`,
    year: "Έτος",
    label: "Δισκογραφική",
    catalog: "Αρ. καταλόγου",
    format: "Μορφή",
    performers: "Ερμηνεύουν",
    lyricists: "Στίχοι / Ποίηση",
    sideA: "Πλευρά Α",
    sideB: "Πλευρά Β",
    tracklist: "Τα τραγούδια του δίσκου",
    storyBadge: "Διάβασε την ιστορία",
    noStoryNote:
      "Τραγούδια χωρίς σύνδεσμο: δεν έχουμε βρει ακόμη πηγή που να τεκμηριώνει την ιστορία τους — γι' αυτό δεν γράφουμε τίποτα γι' αυτά, μόνο τα στοιχεία του δίσκου.",
    aboutAlbum: "Για τον δίσκο",
    documentHeading: "Ντοκουμέντο από το αρχείο",
    interviewsHeading: "Συνεντεύξεις & ντοκουμέντα",
    interviewsIntro:
      "Βίντεο από το επίσημο Αρχείο της ΕΡΤ — ο ίδιος ο συνθέτης και οι συνεργάτες του μιλούν για το έργο του.",
    discographyHeading: "Δισκογραφία",
    sourcesHeading: "Πηγές",
    prev: "← Προηγούμενος δίσκος",
    next: "Επόμενος δίσκος →",
    decade: (d) => `Δεκαετία του '${String(d).slice(2)}`,
    kinds: {
      all: "Όλα",
      cycle: "Κύκλοι τραγουδιών",
      film: "Κινηματογράφος",
      theatre: "Θέατρο",
      instrumental: "Ορχηστρικά",
      rebetiko: "Ρεμπέτικα",
      anthology: "Ανθολογίες",
    },
    discogsLabel: "Discogs — πλήρης δισκογραφική καταγραφή",
    sleeveNote:
      "Τα εξώφυλλα εδώ είναι δικά μας τυπογραφικά σχέδια, εμπνευσμένα από τα ελληνικά LP των '60s — όχι τα πρωτότυπα, που ανήκουν στους δημιουργούς τους.",
    songsWithStory: (n) => `${n} με ιστορία`,
    tracks: (n) => `${n} τραγούδια`,
    lyrAbbr: "στ.",
    origAbbr: "πρωτότυπο:",
    composerPageTitle: (name) => `${name} — Δισκογραφία & ιστορίες`,
  },
  en: {
    discographies: "Discographies",
    discographiesKicker: "The record archive",
    discographiesIntro:
      "Complete discographies, record by record: who sang, who wrote the lyrics, when and on which label it came out — and, wherever there's a source, the story behind the songs.",
    openFile: "Open the file →",
    albumsCount: (n) => `${n} records in the archive`,
    composer: "Composer",
    backToComposer: (name) => `← All records: ${name}`,
    year: "Year",
    label: "Label",
    catalog: "Catalog no.",
    format: "Format",
    performers: "Performed by",
    lyricists: "Lyrics / Poetry",
    sideA: "Side A",
    sideB: "Side B",
    tracklist: "The songs on the record",
    storyBadge: "Read the story",
    noStoryNote:
      "Songs without a link: we haven't yet found a source documenting their story — so we write nothing about them, only the record's details.",
    aboutAlbum: "About the record",
    documentHeading: "A document from the archive",
    interviewsHeading: "Interviews & documentaries",
    interviewsIntro:
      "Videos from the official ERT Archive (Greek public broadcaster) — the composer himself and his collaborators talk about his work.",
    discographyHeading: "Discography",
    sourcesHeading: "Sources",
    prev: "← Previous record",
    next: "Next record →",
    decade: (d) => `The ${d}s`,
    kinds: {
      all: "All",
      cycle: "Song cycles",
      film: "Film",
      theatre: "Theatre",
      instrumental: "Instrumental",
      rebetiko: "Rebetiko",
      anthology: "Anthologies",
    },
    discogsLabel: "Discogs — full discographic record",
    sleeveNote:
      "The sleeves shown here are our own typographic designs, inspired by 1960s Greek LPs — not the original covers, which belong to their creators.",
    songsWithStory: (n) => `${n} with a story`,
    tracks: (n) => `${n} songs`,
    lyrAbbr: "lyrics:",
    origAbbr: "original by",
    composerPageTitle: (name) => `${name} — Discography & stories`,
  },
};

export function getDiscDict(lang) {
  return discDict[lang] || discDict.el;
}
