// Κείμενα διεπαφής για τις σελίδες δισκογραφίας (συνθέτης / δίσκος).
export const discDict = {
  el: {
    discographies: "Δισκογραφίες",
    discographiesKicker: "Το αρχείο των δίσκων",
    discographiesIntro:
      "Ολόκληρες δισκογραφίες, δίσκο-δίσκο: ποιος τραγούδησε, ποιος έγραψε τους στίχους, πότε και σε ποια εταιρεία κυκλοφόρησε — και, όπου υπάρχει πηγή, η ιστορία πίσω από τα τραγούδια.",
    openFile: "Άνοιξε τον φάκελο →",
    albumsCount: (n) => `${n} δίσκοι στο αρχείο`,
    composer: "Συνθέτης",
    backToComposer: (name) => `← Όλοι οι δίσκοι: ${name}`,
    year: "Έτος",
    label: "Δισκογραφική",
    catalog: "Αρ. καταλόγου",
    format: "Μορφή",
    performers: "Ερμηνεύουν",
    lyricists: "Στίχοι / Ποίηση",
    sideA: "Πλευρά Α",
    sideB: "Πλευρά Β",
    tracklist: "Τα τραγούδια του δίσκου",
    storyBadge: "Διάβασε την ιστορία",
    noStoryNote:
      "Κάθε τραγούδι έχει τη δική του σελίδα. Όσα δεν έχουν την ετικέτα «Διάβασε την ιστορία» δεν έχουν ακόμη τεκμηριωμένη ιστορία — εκεί θα βρεις μόνο τα στοιχεία τους και τους δίσκους όπου εμφανίζονται. Τα ορχηστρικά μέρη δεν έχουν σελίδα.",
    aboutAlbum: "Για τον δίσκο",
    documentHeading: "Ντοκουμέντο από το αρχείο",
    interviewsHeading: "Συνεντεύξεις & ντοκουμέντα",
    interviewsIntro:
      "Βίντεο από το επίσημο Αρχείο της ΕΡΤ — ο ίδιος ο συνθέτης και οι συνεργάτες του μιλούν για το έργο του.",
    discographyHeading: "Δισκογραφία",
    sourcesHeading: "Πηγές",
    prev: "← Προηγούμενος δίσκος",
    next: "Επόμενος δίσκος →",
    decade: (d) => `Δεκαετία του '${String(d).slice(2)}`,
    kinds: {
      all: "Όλα",
      cycle: "Κύκλοι τραγουδιών",
      film: "Κινηματογράφος",
      theatre: "Θέατρο",
      instrumental: "Ορχηστρικά",
      rebetiko: "Ρεμπέτικα",
      anthology: "Ανθολογίες",
    },
    discogsLabel: "Discogs — πλήρης δισκογραφική καταγραφή",
    sleeveNote:
      "Τα εξώφυλλα εδώ είναι δικά μας τυπογραφικά σχέδια, εμπνευσμένα από τα ελληνικά LP των '60s. Τα πρωτότυπα — συχνά έργα ζωγράφων όπως ο Μόραλης, ο Τσαρούχης, ο Φασιανός — ανήκουν στους δημιουργούς τους· σε κάθε δίσκο θα βρεις σύνδεσμο για να τα δεις στην πηγή.",
    songsWithStory: (n) => `${n} με ιστορία`,
    tracks: (n) => `${n} τραγούδια`,
    lyrAbbr: "στ.",
    originalCover: "Το πρωτότυπο εξώφυλλο",
    origAbbr: "πρωτότυπο:",
    composerPageTitle: (name) => `${name} — Δισκογραφία & ιστορίες`,
  },
  en: {
    discographies: "Discographies",
    discographiesKicker: "The record archive",
    discographiesIntro:
      "Complete discographies, record by record: who sang, who wrote the lyrics, when and on which label it came out — and, wherever there's a source, the story behind the songs.",
    openFile: "Open the file →",
    albumsCount: (n) => `${n} records in the archive`,
    composer: "Composer",
    backToComposer: (name) => `← All records: ${name}`,
    year: "Year",
    label: "Label",
    catalog: "Catalog no.",
    format: "Format",
    performers: "Performed by",
    lyricists: "Lyrics / Poetry",
    sideA: "Side A",
    sideB: "Side B",
    tracklist: "The songs on the record",
    storyBadge: "Read the story",
    noStoryNote:
      "Every song has its own page. Those without the “Read the story” tag don't have a documented story yet — there you'll find only their details and the records they appear on. Instrumental pieces have no page.",
    aboutAlbum: "About the record",
    documentHeading: "A document from the archive",
    interviewsHeading: "Interviews & documentaries",
    interviewsIntro:
      "Videos from the official ERT Archive (Greek public broadcaster) — the composer himself and his collaborators talk about his work.",
    discographyHeading: "Discography",
    sourcesHeading: "Sources",
    prev: "← Previous record",
    next: "Next record →",
    decade: (d) => `The ${d}s`,
    kinds: {
      all: "All",
      cycle: "Song cycles",
      film: "Film",
      theatre: "Theatre",
      instrumental: "Instrumental",
      rebetiko: "Rebetiko",
      anthology: "Anthologies",
    },
    discogsLabel: "Discogs — full discographic record",
    sleeveNote:
      "The sleeves shown here are our own typographic designs, inspired by 1960s Greek LPs. The originals — often works by painters such as Moralis, Tsarouchis, Fassianos — belong to their creators; every record page links to them at the source.",
    songsWithStory: (n) => `${n} with a story`,
    tracks: (n) => `${n} songs`,
    lyrAbbr: "lyrics:",
    originalCover: "The original cover",
    origAbbr: "original by",
    composerPageTitle: (name) => `${name} — Discography & stories`,
  },
};

export function getDiscDict(lang) {
  return discDict[lang] || discDict.el;
}
